### ISSUE TITLE
Is there "rf2o_laser_odometry" package for ROS2?

### ISSUE THREAD

**Issue by harderthan** [aws-deepracer/aws-deepracer#4]
I'm trying to follow the guide with `deepracer_bringup` package.
It run a `rf2o_laser_odometry_node` node  for odometry on [`deepracer.launch.py`](https://github.com/aws-deepracer/aws-deepracer/blob/0b59c0e2d6e7837338f3f20636d0fda92235195a/deepracer_bringup/launch/deepracer.launch.py#L91) of `deepracer_bringup` package. 
But, I couldn't find the package, which be able to built with ROS2, not ROS1.
Is there "rf2o_laser_odometry" package for ROS2?

Thanks.

**Comment by pratik-nichat** [comment]
Hello @harderthan,
Thank you for your interest in AWS DeepRacer. Regarding your query, the `rf2o_laser_odometry_node` can be downloaded using the instructions provided to [Clone and build the robot packages on the AWS DeepRacer device](https://github.com/aws-deepracer/aws-deepracer/blob/main/introduction-to-the-ros-navigation-stack-using-aws-deepracer-evo.md#part-21--clone-and-build-the-robot-packages-on-the-aws-deepracer-device) specifically section 2.1.4 where we install the [dependencies](https://github.com/aws-deepracer/aws-deepracer/blob/main/deepracer_nodes/install_dependencies.sh).

Please let us know if you have any other questions. Thanks!
