### ISSUE TITLE
An unknown part in the DeepRacer Evo Kit

### ISSUE THREAD

**Issue by franky920920** [aws-deepracer/aws-deepracer#5]
Is anyone know what is this part in the DeepRacer Evo Kit. We got 10 DeepRacer and its Evo kit here and we have no idea what it is. Any help would be appreciated. Thank you! 
<img width="798" alt="Screen Shot 2022-03-17 at 10 13 30 AM" src="https://user-images.githubusercontent.com/11349917/158724999-c9af8eca-8866-40a0-b271-ceabd3d7e4aa.png">

**Comment by siddalingesha-ds** [comment]
Hi, 

It is not a functional part of the car, and not necessary to get the Sensor kit attached. 

Thanks,
Siddalingesha D S

**Comment by robodhruv** [comment]
Just out of curiosity, what is that part for? Curious why it was included...

**Comment by davidfsmith** [comment]
Hello,

It's a spacer to go on the end of the Asus powerbank

Regards
Dave
