### ISSUE TITLE
rplidar_ros2 package gives 404 page not found 

### ISSUE THREAD

**Issue by zekailin00** [aws-deepracer/aws-deepracer#6]
Hi,

I am installing this package into the deep racer device. But when I open the https://github.com/youngday/rplidar_ros2 , it is 404 not found. Is there is a way to get the package? 

Thanks,
Zekai

**Comment by pratik-nichat** [comment]
Hello @zekailin00 ,
Thank you for going through the AWS DeepRacer GitHub repositories. We have updated the rplidar dependency. Could you please try again after pulling from the latest again?
